[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "always"
startCommand = "chmod +x start_simple.sh && ./start_simple.sh"
restartPolicyMaxRetries = 10
